name: Cache fonts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # weekly, every Sunday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check cache
        id: cache
        uses: actions/cache@v4
        with:
          path: fonts-bin
          key: fonts

      - name: Setup Fontist
        if: steps.cache.outputs.cache-hit != 'true'
        uses: fontist/setup-fontist@v2

      - name: Check if Iosevka is available
        run: |
          fontist list "Iosevka"
          fontlist list -all | grep -i "Iosevka"
          if ! fontist list "Iosevka" || ! fontlist list -all | grep -i "Iosevka"; then
            echo "Iosevka is not available in Fontist. Please check the font name and try again."
            exit 1
          fi

      - name: Install Iosevka
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          fontist install "Iosevka"
          mkdir -p fonts-bin
          cp -r ~/.fontist/fonts/* fonts-bin/