name: Cache fonts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # weekly, every Sunday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check cache
        id: cache
        uses: actions/cache@v4
        with:
          path: fonts-bin
          key: fonts

      - name: Download Iosevka
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p fonts-bin
          curl -L https://github.com/be5invis/Iosevka/releases/latest/download/PkgTTF-IosevkaTerm-Regular.zip -o iosevka.zip
          unzip iosevka.zip -d fonts-bin/
          rm iosevka.zip